exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^notebooks/
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/myint/autoflake.git
#   rev: v1.4
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,


## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.8.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
      exclude: ^notebooks/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: flake8
      exclude: ^notebooks/

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.2
  hooks:
    - id: reorder-python-imports
      application-directories: src
      exclude: ^notebooks/

- repo: local
  hooks:
    - id: format-ipynb
      name: format-ipynb
      entry: jupytext --from ipynb --pipe black --check flake8 --pre-commit
      pass_filenames: false
      language: python
    - id: jupytext
      name: jupytext
      entry: jupytext --from ipynb --to py:light --pre-commit
      pass_filenames: false
      language: python
