name: arcade
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.8.5
  - pip
  - pip-tools
  # Above, list any packages that MUST be installed via conda
  - pip:
    # Install all pip-installable packages
    # - -r file:requirements.txt
